config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#top'
  get 'signup', to: 'users#new'
  
  # ログイン機能
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  # ログインボタン(管理者、一般ユーザー)
  patch 'login', to: 'sessions#admin_login'
  put 'login', to: 'sessions#general_login'
  
  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      get 'one_week'
      get 'attendances/edit_one_week'
      patch 'attendances/update_one_week'
      
    end
    resources :attendances, only: :update
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  # ユーザー名による絞り込み
  scope :get_by_name, ->(name) {
  where("name like ?", "%#{name}%")
  }
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :department, length: { in: 2..30 }, allow_blank: true
  validates :basic_time, presence: true
  validates :work_time, presence: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
 
  
  def User.digest(string)
    cost = 
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end
  
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::password.new(remember_digest).is_password?(remember_token)
  end
  
   # ユーザーのログイン情報を破棄します。
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i(show edit update destroy edit_basic_info update_basic_info one_week)
  before_action :logged_in_user, only: %i(index show edit update destroy edit_basic_info update_basic_info)
  before_action :correct_user, only: %i(edit update)
  before_action :admin_user, only: %i(index destroy edit_basic_info update_basic_info edit_one_week)
  before_action :set_one_month, only: %i(show)
  before_action :set_one_week, only: %i(one_week)
  before_action :admin_or_correct_user, only: %i(show one_week)
  
  def index
    @users = User.paginate(page: params[:page])
      if params[:name].present?
        @users = @users.get_by_name params[:name]
      end
  end
  
  def show
    @worked_sum = @attendances.where.not(finished_at: nil).count
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = '新規作成に成功しました。'
      redirect_to @user
    else
      render :new
    end
  end
    
  def edit
  end
  
  def update
    if @user.update_attributes(user_params)
      flash[:success] = "アカウント情報を更新しました。"
      redirect_to @user
    else
      render :edit
    end
  end
  
  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end
  
  def edit_basic_info
  end
  
  def update_basic_info
    if @user.update_attributes(basic_info_params)
      flash[:success] = "#{@user.name}の基本情報を更新しました。"
    else
      flash[:danger] = "#{@user.name}の更新は失敗しました。<br>" + @user.errors.full_messages.join("<br>")
    end
    redirect_to @user
  end
  
  def one_week
    @worked_sum = @attendances.where.not(finished_at: nil).count
  end
  
  private
  
    def user_params
      params.require(:user).permit(:name, :email, :department, :password, :password_confirmation)
    end
    
    def basic_info_params
       params.require(:user).permit(:department, :basic_time, :work_time)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  
  # 勤怠基本情報を指定のフォーマットで返す。
  def format_basic_info(time)
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end
end

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages', object: @user %>
  
  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>
  
  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>
  
  <%= f.label :department, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :department, class: "form-control" %>
  
  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>
  
  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>
  
  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
  
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text, '更新') %>
<h1>アカウント情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit_basic_info.html.erb
<% provide(:title, "edit_basic_info") %>
<% provide(:class_text, 'basic-info') %>
<h1>基本情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, url: update_basic_info_user_path(@user), local: true, method: :patch) do |f| %>
      <%= render 'shared/error_messages', object: @user %>
    
      <%= f.label :work_time, "指定勤務時間", class: "label-#{yield(:class_text)}" %>
      <%= f.time_field :work_time, class: 'form-control' %>
      
      <%= f.label :basic_time, "基本時間", class: "label-#{yield(:class_text)}" %>
      <%= f.time_field :basic_time, class: 'form-control' %>
      
      <%= f.submit "編集", class: "btn btn-primary btn-block btn-user--edit" %>
    <% end %>
    
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>

<% if params[:name].present? %>
  <h1>検索結果</h1>
<% else %>
  <h1>ユーザー覧</h1>
<% end %>
<div class="col-md-10 col-md-offset-1">
  <%= will_paginate %>
  <div class="pull-right">
    <%= form_tag(users_path, method: "get") do %>
    <%= label_tag :name, "ユーザー検索" %><br>
    <%= text_field_tag :name, params[:name], class: "form-search" %>
    <%= submit_tag "検索", class: "btn btn-primary" %>
    <% end %>
  </div>
  <table class="table table-condensed table-hover" id="table-users">
    <thead>
      <tr>
        <th><%= User.human_attribute_name :name %></th>
        <% if current_user.admin? %>
          <th class="center"><%= User.human_attribute_name :basic_time %></th>
          <th class="center"><%= User.human_attribute_name :work_time %></th>
        <% end %>
      </tr>
    </thead>
    
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user %></td>
        <% if current_user.admin? %>
          <td class="center"><%= format_basic_info(user.basic_time) %></td>
          <td class="center"><%= format_basic_info(user.work_time) %></td>
        <% end %>
        <td>
          <% if current_user.admin? && !current_user?(user) %>
            <%= link_to "基本情報編集", edit_basic_info_user_path(user), class: "btn btn-success" %>
            <%= link_to "削除", user, method: :delete,
                data: { confirm: "削除してよろしいですか？" },
                class: "btn btn-danger pull-right" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'sign up') %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '作成') %>
<h1>アカウント作成</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/one_week.html.erb
<% provide(:title, @user.name) %>
<div>
  <table class = "table table-bordered table-condensed user-table">
    <tr>
      <td>
          <%= link_to "◀", one_week_user_path(date: @first_day.prev_week), class: "btn btn-info" %>
         【<%= l(@first_day, format: :middle) %>】勤怠管理表
          <%= link_to "▶", one_week_user_path(date: @first_day.next_week), class: "btn btn-info" %>
     </td>
      <td>【<%= l(@first_day, format: :middle) %>】勤怠管理表</td>
      <td>指定勤務時間  <%= format_basic_info(@user.work_time) %></td>
      <td>基本時間  <%= format_basic_info(@user.basic_time) %></td>
      <td>初日  <%= l(@first_day, format: :short) %></td>
    </tr>
    
    <tr>
      <td>所属  <%= @user.department.present? ? @user.department : "未所属" %></td>
      <td>氏名  <%= @user.name %></td>
      <td>コード 000</td>
      <td>出勤日数  <%= @worked_sum %>日</td>
      <td>締め  <%= l(@last_day, format: :short) %></td>
    </tr>
  </table>
  
  
</div>

<div class="btn-users-show">
  <%= link_to "勤怠を編集", attendances_edit_one_week_user_path(date: @first_day), class: "btn btn-info" %>
  <%= link_to "月間表示に切替", current_user, class: "btn btn-info pull-right" %>
</div>

<div>
  <table class="table table-bordered table-condensed table-hover" id="table-attendances">
    <thead>
      <tr>
        <th rowspan="2" class="col-md-1">日付</th>
        <th rowspan="2" class="col-md-1">曜日</th>
        <th colspan="3">出社</th>
        <th colspan="3">退社</th>
        <th rowspan="2" class="col-md-2">在社時間</th>
        <th rowspan="2">備考</th>
      </tr>
      <tr>
       <th class="col-md-1">時</th>
       <th class="col-md-1">分</th>
       <th class="col-md-1"></th>
       <th class="col-md-1">時</th>
       <th class="col-md-1">分</th>
       <th class="col-md-1"></th>
      </tr>
    </thead>
    
    <tbody>
      <% @attendances.each do |day| %>
        <tr>
          <td><%= l(day.worked_on, format: :short) %></td>
          <td>
              <% if day.worked_on.wday == 1 %>
               <%= $days_of_the_week[day.worked_on.wday] %>
              <% end %>
              
              <% if day.worked_on.wday == 2 %>
               <%= $days_of_the_week[day.worked_on.wday] %>
              <% end %>
            
              <% if day.worked_on.wday == 3 %>
               <%= $days_of_the_week[day.worked_on.wday] %>
              <% end %>
              
              <% if day.worked_on.wday == 4 %>
               <%= $days_of_the_week[day.worked_on.wday] %>
              <% end %>
              
              <% if day.worked_on.wday == 5 %>
               <%= $days_of_the_week[day.worked_on.wday] %>
              <% end %>
              
              <% if day.worked_on.wday == 6 %>
               <font color=“blue”><%= $days_of_the_week[day.worked_on.wday] %></font>
              <% end %>
             
              <% if day.worked_on.wday == 0 %>
               <font color=#F00><%= $days_of_the_week[day.worked_on.wday] %></font>
              <% end %>
          </td>
          <td><%= l(day.started_at, format: :hour) if day.started_at.present? %></td>
          <td><%= day.started_at.min.floor_to(15) if day.started_at.present? %></td>
          <td>
            <% if btn_text = attendance_state_started(day) %>
              <%= link_to "#{btn_text}", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-attendance" %>
            <% end %>
          </td>
          <td><%= l(day.finished_at, format: :hour) if day.finished_at.present? %></td>
          <td><%= day.finished_at.min.floor_to(15) if day.finished_at.present? %></td>
          <td>
            <% if btn_text = attendance_state_finished(day) %>
              <%= link_to "#{btn_text}", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-attendance" %>
            <% end %>
          </td>
          <td>
            <% if day.started_at.present? && day.finished_at.present? %>
              <%= str_times = working_times(day.started_at.floor_to(15.minutes), day.finished_at.floor_to(15.minutes)) %>
              <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
            <% end %>
          </td>
          <td><%= day.note %></td>
        </tr>
      <% end %>
    </tbody>
    
    <rfoot>
      <!--rowspan:縦結合、colspan:横結合-->
      <tr>
        <td colspan="4">累計日数</td>
        <td colspan="4">総合勤務時間</td>
        <td colspan="4">累計在社時間</td>
      </tr>
      <tr>
        <td colspan="4"><%= @attendances.count %></td>
        <td colspan="4"><%= format_basic_info(@user.work_time).to_f * @worked_sum %></td>
        <td colspan="4"><%= format("%.2f", @total_working_times.to_f) %></td>
      </tr>
    </rfoot>
  </table>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div>
  <table class = "table table-bordered table-condensed user-table">
    <tr>
      <td>
          <%= link_to "◀", user_path(date: @first_day.prev_month), class: "btn btn-info" %>
         【<%= l(@first_day, format: :middle) %>】勤怠管理表
          <%= link_to "▶", user_path(date: @first_day.next_month), class: "btn btn-info" %>
     </td>
      <td>【<%= l(@first_day, format: :middle) %>】勤怠管理表</td>
      <td>指定勤務時間  <%= format_basic_info(@user.work_time) %></td>
      <td>基本時間  <%= format_basic_info(@user.basic_time) %></td>
      <td>初日  <%= l(@first_day, format: :short) %></td>
    </tr>
    
    <tr>
      <td>所属  <%= @user.department.present? ? @user.department : "未所属" %></td>
      <td>氏名  <%= @user.name %></td>
      <td>コード 000</td>
      <td>出勤日数  <%= @worked_sum %>日</td>
      <td>締め  <%= l(@last_day, format: :short) %></td>
    </tr>
  </table>
  
  
</div>

<div class="btn-users-show">
  <%= link_to "勤怠を編集", attendances_edit_one_month_user_path(date: @first_day), class: "btn btn-info" %>
  <%= link_to "週間表示に切替", one_week_user_path, class: "btn btn-info pull-right" %>
</div>

<div>
  <table class="table table-bordered table-condensed table-hover" id="table-attendances">
    <thead>
      <tr>
        <th rowspan="2" class="col-md-1">日付</th>
        <th rowspan="2" class="col-md-1">曜日</th>
        <th colspan="3">出社</th>
        <th colspan="3">退社</th>
        <th rowspan="2" class="col-md-2">在社時間</th>
        <th rowspan="2">備考</th>
      </tr>
      <tr>
       <th class="col-md-1">時</th>
       <th class="col-md-1">分</th>
       <th class="col-md-1"></th>
       <th class="col-md-1">時</th>
       <th class="col-md-1">分</th>
       <th class="col-md-1"></th>
      </tr>
    </thead>
    
    <tbody>
      <% @attendances.each do |day| %>
        <tr>
          <td><%= l(day.worked_on, format: :short) %></td>
          <td>
              <% if day.worked_on.wday == 1 %>
               <%= $days_of_the_week[day.worked_on.wday] %>
              <% end %>
              
              <% if day.worked_on.wday == 2 %>
               <%= $days_of_the_week[day.worked_on.wday] %>
              <% end %>
            
              <% if day.worked_on.wday == 3 %>
               <%= $days_of_the_week[day.worked_on.wday] %>
              <% end %>
              
              <% if day.worked_on.wday == 4 %>
               <%= $days_of_the_week[day.worked_on.wday] %>
              <% end %>
              
              <% if day.worked_on.wday == 5 %>
               <%= $days_of_the_week[day.worked_on.wday] %>
              <% end %>
              
              <% if day.worked_on.wday == 6 %>
               <font color=“blue”><%= $days_of_the_week[day.worked_on.wday] %></font>
              <% end %>
             
              <% if day.worked_on.wday == 0 %>
               <font color=#F00><%= $days_of_the_week[day.worked_on.wday] %></font>
              <% end %>
          </td>
          <td><%= l(day.started_at, format: :hour) if day.started_at.present? %></td>
          <td><%= day.started_at.min.floor_to(15) if day.started_at.present? %></td>
          <td>
            <% if btn_text = attendance_state_started(day) %>
              <%= link_to "#{btn_text}", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-attendance" %>
            <% end %>
          </td>
          <td><%= l(day.finished_at, format: :hour) if day.finished_at.present? %></td>
          <td><%= day.finished_at.min.floor_to(15) if day.finished_at.present? %></td>
          <td>
            <% if btn_text = attendance_state_finished(day) %>
              <%= link_to "#{btn_text}", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-attendance" %>
            <% end %>
          </td>
          <td>
            <% if day.started_at.present? && day.finished_at.present? %>
              <%= str_times = working_times(day.started_at.floor_to(15.minutes), day.finished_at.floor_to(15.minutes)) %>
              <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
            <% end %>
          </td>
          <td><%= day.note %></td>
        </tr>
      <% end %>
    </tbody>
    
    <rfoot>
      <!--rowspan:縦結合、colspan:横結合-->
      <tr>
        <td colspan="4">累計日数</td>
        <td colspan="4">総合勤務時間</td>
        <td colspan="4">累計在社時間</td>
      </tr>
      <tr>
        <td colspan="4"><%= @attendances.count %></td>
        <td colspan="4"><%= format_basic_info(@user.work_time).to_f * @worked_sum %></td>
        <td colspan="4"><%= format("%.2f", @total_working_times.to_f) %></td>
      </tr>
    </rfoot>
  </table>
</div>