config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#top'
  get 'signup', to: 'users#new'
  
  # ログイン機能
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  # ログインボタン(管理者、一般ユーザー)
  patch 'login', to: 'sessions#admin_login'
  put 'login', to: 'sessions#general_login'
  
  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      get 'one_week'
      get 'attendances/edit_one_week'
      patch 'attendances/update_one_week'
      
    end
    resources :attendances, only: :update
  end
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  
  validates :worked_on, presence: true
  validates :note, length: { maximum: 50 }
  
  # 出勤時間が存在しない場合、退勤時間は無効
  validate :finished_at_is_invalid_without_a_started_at
  # 出勤と退勤時間がどちらも存在するとき、出勤時間より早い退勤時間は無効
  validate :started_at_than_finished_at_fast_if_invalid
  
  def finished_at_is_invalid_without_a_started_at
    errors.add(:started_at, "が必要です。") if started_at.blank? && finished_at.present?
  end
  
  def started_at_than_finished_at_fast_if_invalid
    if started_at.present? && finished_at.present?
      errors.add(:started_at, "より早い時間は無効です。") if started_at > finished_at
    end
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
include AttendancesHelper
  before_action :set_user, only: %i(edit_one_month update_one_month edit_one_week update_one_week)
  before_action :logged_in_user, only: %i(update edit_one_month edit_one_week)
  before_action :admin_or_correct_user, only: %i(update edit_one_month update_one_month edit_one_week update_one_week)
  before_action :set_one_month, only: %i(edit_one_month)
  before_action :set_one_week, only: %i(edit_one_week)
  
  UPDATE_ERROR_MSG = "勤怠登録に失敗しました。やり直してください。"
  
  def update
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:id])
    # 出勤時間が未登録であることを判定。
    if @attendance.started_at.nil?
      if @attendance.update_attributes(started_at: Time.current.floor_to(15.minutes))
        flash[:info] = "おはようございます！"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    elsif @attendance.finished_at.nil?
      if @attendance.update_attributes(finished_at: Time.current.floor_to(15.minutes))
        flash[:info] = "お疲れ様でした。"
      else
        flash[:info] = UPDATE_ERROR_MSG
      end
    end
    redirect_to @user
  end
  
  def edit_one_month
  end
  
  def update_one_month
    ActiveRecord::Base.transaction do
      if attendances_invalid?
        attendances_params.each do |id, item|
          attendance = Attendance.find(id)
          attendance.update_attributes!(item)
      end
        flash[:success] = "1ヶ月分の勤怠情報を更新しました。"
        redirect_to user_url(date: params[:date])
      else
        flash[:danger] = "無効な入力データがあった為、更新をキャンセルしました。"
        redirect_to attendances_edit_one_month_user_url(date: params[:date])
      end
    rescue ActiveRecord::RecordInvalid
      flash[:danger] = "無効な入力データがあった為、更新をキャンセルしました。"
      redirect_to attendances_edit_one_month_user_url(date: params[:date])
    end
  end
  
  def edit_one_week
  end
  
  def update_one_week
     ActiveRecord::Base.transaction do
      if attendances_invalid?
        attendances_params.each do |id, item|
          attendance = Attendance.find(id)
          attendance.update_attributes!(item)
      end
        flash[:success] = "1週間分の勤怠情報を更新しました。"
        redirect_to user_url(date: params[:date])
      else
        flash[:danger] = "無効な入力データがあった為、更新をキャンセルしました。"
        redirect_to attendances_edit_one_week_user_url(date: params[:date])
      end
    rescue ActiveRecord::RecordInvalid
      flash[:danger] = "無効な入力データがあったため、更新をキャンセルしました。"
      redirect_to attendances_edit_one_week_user_url(date: params[:date])
    end
  end
  
  private
  
    def attendances_params
      params.require(:user).permit(attendances: [:started_at, :finished_at, :note])[:attendances]
    end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
  
  def attendance_state_started(attendance)
    if Date.current == attendance.worked_on
      return '出社' if attendance.started_at.nil?
    end
    false
  end
  
  def attendance_state_finished(attendance)
    if Date.current == attendance.worked_on
      return '退社' if attendance.started_at.present? && attendance.finished_at.nil?
    end
    false
  end
  
  def working_times(start, finish)
    format("%.2f", (((finish - start) / 60) / 60.0))
  end

   # 不正な値があるか確認する
  def attendances_invalid?
    attendances = true
    attendances_params.each do |id, item|
      if item[:started_at].blank? && item[:finished_at].blank?
        next
      elsif item[:started_at].blank? || item[:finished_at].blank?
        attendances = false
        break
      elsif item[:started_at] > item[:finished_at]
        attendances = false
        break
      end
    end
    return attendances
  end
end

app/views/attendances/edit_one_month.html.erb
<% provide(:title, @user.name) %>
<%= form_with(model: @user, url: attendances_update_one_month_user_path(date: @first_day), local: true, method: :patch) do |f| %>
  <div>
    <h1>勤怠編集画面</h1>
    <table class="table table-bordered table-condensed table-hover" id="table-attendances">
      <thead>
        <tr>
          <th>日付</th>
          <th>曜日</th>
          <th>出社</th>
          <th>退社</th>
          <th>在社時間</th>
          <th>備考</th>
        </tr>
      </thead>
      <tbody>
        <% @attendances.each do |day| %>
          <%= f.fields_for "attendances[]", day do |attendance| %>
            <tr>
              <td><%= l(day.worked_on, format: :short) %></td>
              <td>
                 <% if day.worked_on.wday == 1 %>
                  <%= $days_of_the_week[day.worked_on.wday] %>
                 <% end %>
                 
                 <% if day.worked_on.wday == 2 %>
                  <%= $days_of_the_week[day.worked_on.wday] %>
                 <% end %>
               
                 <% if day.worked_on.wday == 3 %>
                  <%= $days_of_the_week[day.worked_on.wday] %>
                 <% end %>
                 
                 <% if day.worked_on.wday == 4 %>
                  <%= $days_of_the_week[day.worked_on.wday] %>
                 <% end %>
                 
                 <% if day.worked_on.wday == 5 %>
                  <%= $days_of_the_week[day.worked_on.wday] %>
                 <% end %>
                 
                 <% if day.worked_on.wday == 6 %>
                  <font color=“blue”><%= $days_of_the_week[day.worked_on.wday] %></font>
                 <% end %>
                
                 <% if day.worked_on.wday == 0 %>
                  <font color=#F00><%= $days_of_the_week[day.worked_on.wday] %></font>
                 <% end %>
              </td>
              <% if (Date.current < day.worked_on) %>
                <td><%= attendance.time_field :started_at, readonly: true, class: "form-control" %></td>
                <td><%= attendance.time_field :finished_at, readonly: true, class: "form-control" %></td>
              <% else %>
                <td><%= attendance.time_field :started_at, class: "form-control" %></td>
                <td><%= attendance.time_field :finished_at, class: "form-control" %></td>
              <% end %>
              <td>
                <% if day.started_at.present? && day.finished_at.present? %>
                  <%= working_times(day.started_at, day.finished_at) %>
                <% end %>
              </td>
              <td><%= attendance.text_field :note, class: "form-control" %></td>
            </tr>
          <% end %>
         <% end %>
      </tbody>
    </table>
  </div>
  
  <div class="center">
    <%= f.submit "まとめて更新", class: "btn btn-lg btn-primary" %>
    <%= link_to "キャンセル", user_path(date: @first_day), class: "btn btn-lg btn-default" %>
  </div>
<% end %>

app/views/attendances/edit_one_week.html.erb
<% provide(:title, @user.name) %>
<%= form_with(model: @user, url: attendances_update_one_week_user_path(date: @first_day), local: true, method: :patch) do |f| %>
  <div>
    <h1>勤怠編集画面</h1>
    <table class="table table-bordered table-condensed table-hover" id="table-attendances">
      <thead>
        <tr>
          <th>日付</th>
          <th>曜日</th>
          <th>出社</th>
          <th>退社</th>
          <th>在社時間</th>
          <th>備考</th>
        </tr>
      </thead>
      <tbody>
        <% @attendances.each do |day| %>
          <%= f.fields_for "attendances[]", day do |attendance| %>
            <tr>
              <td><%= l(day.worked_on, format: :short) %></td>
              <td>
                 <% if day.worked_on.wday == 1 %>
                  <%= $days_of_the_week[day.worked_on.wday] %>
                 <% end %>
                 
                 <% if day.worked_on.wday == 2 %>
                  <%= $days_of_the_week[day.worked_on.wday] %>
                 <% end %>
               
                 <% if day.worked_on.wday == 3 %>
                  <%= $days_of_the_week[day.worked_on.wday] %>
                 <% end %>
                 
                 <% if day.worked_on.wday == 4 %>
                  <%= $days_of_the_week[day.worked_on.wday] %>
                 <% end %>
                 
                 <% if day.worked_on.wday == 5 %>
                  <%= $days_of_the_week[day.worked_on.wday] %>
                 <% end %>
                 
                 <% if day.worked_on.wday == 6 %>
                  <font color=“blue”><%= $days_of_the_week[day.worked_on.wday] %></font>
                 <% end %>
                
                 <% if day.worked_on.wday == 0 %>
                  <font color=#F00><%= $days_of_the_week[day.worked_on.wday] %></font>
                 <% end %>
              </td>
              <% if (Date.current < day.worked_on) %>
                <td><%= attendance.time_field :started_at, readonly: true, class: "form-control" %></td>
                <td><%= attendance.time_field :finished_at, readonly: true, class: "form-control" %></td>
              <% else %>
                <td><%= attendance.time_field :started_at, class: "form-control" %></td>
                <td><%= attendance.time_field :finished_at, class: "form-control" %></td>
              <% end %>
              <td>
                <% if day.started_at.present? && day.finished_at.present? %>
                  <%= working_times(day.started_at, day.finished_at) %>
                <% end %>
              </td>
              <td><%= attendance.text_field :note, class: "form-control" %></td>
            </tr>
          <% end %>
         <% end %>
      </tbody>
    </table>
  </div>
  
  <div class="center">
    <%= f.submit "まとめて更新", class: "btn btn-lg btn-primary" %>
    <%= link_to "キャンセル", one_week_user_path(date: @first_day), class: "btn btn-lg btn-default" %>
  </div>
<% end %>